"""Parsing an uploaded LaTeX project archive.

PURE -- no DB, no ORM, no service imports beyond `latex_paths`, exactly like
`latex_paths.py` itself. The caller hands over bytes and gets entries or an
exception; nothing here knows a document exists.

EVERY rejection rejects the WHOLE archive. A partial import produces a project
silently missing the file its `\\input` names, which compiles to a confusing
TeX error the user cannot connect to their upload. A 422 naming the offending
entry is actionable.

The declared size recorded in a zip entry's header is attacker-controlled
metadata and is never trusted: sizes come from counting the bytes actually
decompressed, so a header claiming 1KB in front of 4GB of zeros is caught
while decompressing, not believed.
"""

from __future__ import annotations

import io
import stat
import zipfile
from dataclasses import dataclass

from app.core.config import settings
from app.services.latex_paths import InvalidPath, collision_key, normalize_path

# Read in bounded chunks so an entry is measured as it decompresses rather
# than materialised and then measured.
_CHUNK = 64 * 1024

_JUNK_PREFIXES = ("__MACOSX/", ".git/")
_JUNK_NAMES = (".DS_Store", "Thumbs.db", ".gitignore", ".gitattributes")
# Regenerated by every compile; importing them only consumes quota.
_ARTIFACT_SUFFIXES = (
    ".aux",
    ".log",
    ".out",
    ".synctex.gz",
    ".fls",
    ".fdb_latexmk",
    ".bbl",
    ".blg",
    ".toc",
    ".lof",
    ".lot",
)


@dataclass(frozen=True)
class ArchiveEntry:
    path: str
    data: bytes
    is_binary: bool


class InvalidArchive(Exception):
    """The archive cannot be accepted. `entry` names the offending member
    when one is identifiable -- that name is the only context the user needs
    and the one a generic "invalid archive" message throws away."""

    def __init__(self, reason: str, *, entry: str | None = None) -> None:
        super().__init__(f"{entry}: {reason}" if entry else reason)
        self.reason = reason
        self.entry = entry


class ArchiveTooLarge(InvalidArchive):
    """A size or count bound was crossed. Distinct from InvalidArchive so the
    route can answer 413 rather than 422."""


class EncryptedArchive(InvalidArchive):
    """Password-protected. Distinct so the user is told to re-export rather
    than shown an opaque parse failure."""


def classify_binary(data: bytes) -> bool:
    """True when the bytes are not LaTeX source.

    The NUL check comes FIRST and is not redundant: a file can be valid UTF-8
    and still be binary, and a NUL in what claims to be source is a reliable
    tell. Decided exactly once, here, so no reader downstream has to guess.
    """
    if b"\x00" in data:
        return True
    try:
        data.decode("utf-8")
    except UnicodeDecodeError:
        return True
    return False


def _is_junk(name: str) -> bool:
    if name.startswith(_JUNK_PREFIXES):
        return True
    base = name.rsplit("/", 1)[-1]
    if base in _JUNK_NAMES or base.startswith("._"):
        return True
    return name.endswith(_ARTIFACT_SUFFIXES)


def _common_prefix(names: list[str]) -> str:
    """The single top-level directory every member shares, or "".

    Overleaf, arXiv and GitHub all wrap a project in one directory. Without
    stripping it every stored path carries a junk segment and `main_path`
    reads wrong to the user. Two top-level entries, or any root-level file,
    means there is nothing to strip. A single file is left alone too: a lone
    `chapters/intro.tex` is an ordinary subdirectory, not a wrapper, and
    stripping it would be indistinguishable from that case.
    """
    if len(names) < 2:
        return ""
    tops = {n.split("/", 1)[0] for n in names}
    if len(tops) != 1:
        return ""
    top = tops.pop()
    if not all(n.startswith(f"{top}/") for n in names):
        return ""  # a root-level file named exactly `top`
    return f"{top}/"


def _reject_special(info: zipfile.ZipInfo) -> None:
    """Refuse anything that is not a regular file.

    A symlink's stored CONTENT is its target path; keeping one would hand the
    compiler a way out of the tree. The mode lives in the high 16 bits of
    external_attr and is only meaningful for Unix-created archives.
    """
    if info.create_system != 3:  # not Unix; no mode bits to read
        return
    mode = info.external_attr >> 16
    if stat.S_IFMT(mode) == 0:
        # No file-type bits recorded (e.g. permission-only attrs written by
        # a plain `writestr(name, data)` call) -- nothing to distrust.
        return
    if stat.S_ISLNK(mode):
        raise InvalidArchive("symbolic links are not allowed", entry=info.filename)
    if not stat.S_ISREG(mode) and not stat.S_ISDIR(mode):
        raise InvalidArchive("only regular files are allowed", entry=info.filename)


def _read_bounded(zf: zipfile.ZipFile, info: zipfile.ZipInfo, budget: int) -> bytes:
    """Decompress one entry, aborting the moment it crosses either bound.

    Bounded chunks, not `zf.read(info)`: a declared-small entry can expand
    without limit, and read() would materialise all of it before anyone could
    object.
    """
    per_file = settings.latex_file_max_bytes
    out = bytearray()
    with zf.open(info) as fh:
        while True:
            chunk = fh.read(_CHUNK)
            if not chunk:
                break
            out += chunk
            if len(out) > per_file:
                raise ArchiveTooLarge(
                    f"file exceeds the {per_file} byte limit", entry=info.filename
                )
            if len(out) > budget:
                raise ArchiveTooLarge(
                    f"archive expands past the {settings.latex_project_max_bytes} byte limit",
                    entry=info.filename,
                )
    return bytes(out)


def read_archive(blob: bytes) -> list[ArchiveEntry]:
    """Validate and unpack. Raises on the first problem; never partial."""
    try:
        zf = zipfile.ZipFile(io.BytesIO(blob))
    except zipfile.BadZipFile as exc:
        raise InvalidArchive("not a readable .zip archive") from exc

    with zf:
        infos = zf.infolist()
        # Counted from the central directory BEFORE any decompression, so a
        # hostile archive cannot make us work before we refuse it.
        if len(infos) > settings.latex_max_files:
            raise ArchiveTooLarge(
                f"{len(infos)} entries exceeds the {settings.latex_max_files} entry limit"
            )

        for info in infos:
            if info.flag_bits & 0x1:
                raise EncryptedArchive(
                    "the archive is password-protected; export it without encryption",
                    entry=info.filename,
                )
            _reject_special(info)

        members = [i for i in infos if not i.is_dir()]
        prefix = _common_prefix([i.filename for i in members])

        entries: list[ArchiveEntry] = []
        seen: dict[str, str] = {}
        total = 0
        budget = settings.latex_project_max_bytes

        for info in members:
            name = info.filename[len(prefix) :] if prefix else info.filename
            if not name or _is_junk(name):
                continue
            try:
                path = normalize_path(name)
            except InvalidPath as exc:
                raise InvalidArchive(exc.reason, entry=info.filename) from exc

            key = collision_key(path)
            if key in seen:
                raise InvalidArchive(f"collides with {seen[key]}", entry=info.filename)
            seen[key] = path

            data = _read_bounded(zf, info, budget - total)
            total += len(data)
            entries.append(ArchiveEntry(path=path, data=data, is_binary=classify_binary(data)))

    if not entries:
        raise InvalidArchive("the archive contains no usable files")
    return entries
