"""Parsing an uploaded LaTeX project archive.

PURE -- no DB, no ORM, no service imports beyond `latex_paths`, exactly like
`latex_paths.py` itself. The caller hands over bytes and gets entries or an
exception; nothing here knows a document exists.

EVERY rejection rejects the WHOLE archive. A partial import produces a project
silently missing the file its `\\input` names, which compiles to a confusing
TeX error the user cannot connect to their upload. A 422 naming the offending
entry is actionable.

The declared size recorded in a zip entry's header is attacker-controlled
metadata and is never trusted: sizes come from counting the bytes actually
decompressed, so a header claiming 1KB in front of 4GB of zeros is caught
while decompressing, not believed.

Every raw member name is run through `normalize_path` BEFORE anything else
touches it -- including before the "strip a shared wrapper directory"
convenience and before the junk filter. Computing the shared prefix on raw,
unvalidated names would let a hostile entry's directory component be sliced
away by a sibling and read as accepted; validating first means a traversal,
absolute, or drive-letter entry rejects the whole archive regardless of what
else is in it.
"""

from __future__ import annotations

import io
import stat
import zipfile
import zlib
from dataclasses import dataclass

from app.core.config import settings
from app.services.latex_paths import InvalidPath, collision_key, normalize_path

# Read in bounded chunks so an entry is measured as it decompresses rather
# than materialised and then measured.
_CHUNK = 64 * 1024

# Checked against ANY path segment, not just a leading prefix, so a wrapper
# directory in front of one of these doesn't hide it -- and so one of these
# in front of a real project doesn't poison the wrapper-stripping decision.
_JUNK_DIR_NAMES = frozenset({"__MACOSX", ".git"})
_JUNK_NAMES = (".DS_Store", "Thumbs.db", ".gitignore", ".gitattributes")
# Regenerated by every compile; importing them only consumes quota.
_ARTIFACT_SUFFIXES = (
    ".aux",
    ".log",
    ".out",
    ".synctex.gz",
    ".fls",
    ".fdb_latexmk",
    ".bbl",
    ".blg",
    ".toc",
    ".lof",
    ".lot",
)


@dataclass(frozen=True)
class ArchiveEntry:
    path: str
    data: bytes
    is_binary: bool


class InvalidArchive(Exception):
    """The archive cannot be accepted. `entry` names the offending member
    when one is identifiable -- that name is the only context the user needs
    and the one a generic "invalid archive" message throws away."""

    def __init__(self, reason: str, *, entry: str | None = None) -> None:
        super().__init__(f"{entry}: {reason}" if entry else reason)
        self.reason = reason
        self.entry = entry


class ArchiveTooLarge(InvalidArchive):
    """A size or count bound was crossed. Distinct from InvalidArchive so the
    route can answer 413 rather than 422."""


class EncryptedArchive(InvalidArchive):
    """Password-protected. Distinct so the user is told to re-export rather
    than shown an opaque parse failure."""


def classify_binary(data: bytes) -> bool:
    """True when the bytes are not LaTeX source.

    The NUL check comes FIRST and is not redundant: a file can be valid UTF-8
    and still be binary, and a NUL in what claims to be source is a reliable
    tell. Decided exactly once, here, so no reader downstream has to guess.
    """
    if b"\x00" in data:
        return True
    try:
        data.decode("utf-8")
    except UnicodeDecodeError:
        return True
    return False


def _is_junk(path: str) -> bool:
    """True for a NORMALIZED path that should be silently dropped rather
    than imported: platform/VCS bookkeeping and previous-compile artifacts.
    """
    segments = path.split("/")
    if any(segment in _JUNK_DIR_NAMES for segment in segments):
        return True
    base = segments[-1]
    if base in _JUNK_NAMES or base.startswith("._"):
        return True
    return path.endswith(_ARTIFACT_SUFFIXES)


def _common_prefix(names: list[str]) -> str:
    """The single top-level directory every member shares, or "".

    Overleaf, arXiv and GitHub all wrap a project in one directory. Without
    stripping it every stored path carries a junk segment and `main_path`
    reads wrong to the user. Two top-level entries, or any root-level file,
    means there is nothing to strip.

    Callers must pass already-validated, already-junk-filtered paths: a
    hostile or junk member sitting among real project files must not be able
    to change whether the wrapper gets stripped for everyone else.
    """
    tops = {n.split("/", 1)[0] for n in names}
    if len(tops) != 1:
        return ""
    top = tops.pop()
    if not all(n.startswith(f"{top}/") for n in names):
        return ""  # a root-level file named exactly `top`
    return f"{top}/"


def _reject_special(info: zipfile.ZipInfo) -> None:
    """Refuse anything that is not a regular file.

    A symlink's stored CONTENT is its target path; keeping one would hand the
    compiler a way out of the tree. The mode lives in the high 16 bits of
    external_attr. `create_system` is attacker-controlled metadata and is
    NEVER consulted: an uploader can claim any creator system regardless of
    what bits they actually set, so gating this check on it would make the
    control opt-in for a hostile entry. `S_IFMT(mode) == 0` covers the
    legitimate case with nothing to distrust -- e.g. permission-only attrs
    written by a plain `writestr(name, data)` call.
    """
    mode = info.external_attr >> 16
    if stat.S_IFMT(mode) == 0:
        return
    if stat.S_ISLNK(mode):
        raise InvalidArchive("symbolic links are not allowed", entry=info.filename)
    if not stat.S_ISREG(mode) and not stat.S_ISDIR(mode):
        raise InvalidArchive("only regular files are allowed", entry=info.filename)


def _read_bounded(zf: zipfile.ZipFile, info: zipfile.ZipInfo, budget: int) -> bytes:
    """Decompress one entry, aborting the moment it crosses either bound.

    Bounded chunks, not `zf.read(info)`: a declared-small entry can expand
    without limit, and read() would materialise all of it before anyone could
    object.

    `zipfile`/`zlib` validate and decompress lazily inside `open`/`read`, so a
    malformed entry (corrupt deflate stream, mismatched CRC, mismatched name
    between the local and central headers, an unsupported compression method)
    only surfaces here, not when the archive was first opened. Any of those
    must become an `InvalidArchive`, not an unhandled 500.
    """
    per_file = settings.latex_file_max_bytes
    out = bytearray()
    try:
        with zf.open(info) as fh:
            while True:
                chunk = fh.read(_CHUNK)
                if not chunk:
                    break
                out += chunk
                if len(out) > per_file:
                    raise ArchiveTooLarge(
                        f"file exceeds the {per_file} byte limit", entry=info.filename
                    )
                if len(out) > budget:
                    raise ArchiveTooLarge(
                        f"archive expands past the {settings.latex_project_max_bytes} byte limit",
                        entry=info.filename,
                    )
    except (zipfile.BadZipFile, zlib.error, NotImplementedError, EOFError, RuntimeError) as exc:
        raise InvalidArchive("entry could not be decompressed", entry=info.filename) from exc
    return bytes(out)


def read_archive(blob: bytes) -> list[ArchiveEntry]:
    """Validate and unpack. Raises on the first problem; never partial."""
    try:
        zf = zipfile.ZipFile(io.BytesIO(blob))
    except zipfile.BadZipFile as exc:
        raise InvalidArchive("not a readable .zip archive") from exc

    with zf:
        infos = zf.infolist()
        # Counted from the central directory BEFORE any decompression, so a
        # hostile archive cannot make us DECOMPRESS before we refuse it. This
        # does NOT mean the count is free: `zf.infolist()` above already
        # materialised every ZipInfo, and on a many-entry archive that parse
        # itself is the expensive part (measured: 8.1s / 152MB peak for a
        # 24MB archive of 270,000 empty entries, comfortably under the 25MB
        # body cap). The real control for THAT phase is running this whole
        # function off the event loop in a bounded threadpool -- see
        # `_import_semaphore` in `api/v1/latex_files.py`.
        if len(infos) > settings.latex_max_files:
            raise ArchiveTooLarge(
                f"{len(infos)} entries exceeds the {settings.latex_max_files} entry limit"
            )

        for info in infos:
            if info.flag_bits & 0x1:
                raise EncryptedArchive(
                    "the archive is password-protected; export it without encryption",
                    entry=info.filename,
                )
            _reject_special(info)

        members = [i for i in infos if not i.is_dir()]

        # Validate every member BEFORE any stripping or junk decision -- see
        # the module docstring. `path` here still carries any shared wrapper
        # directory; that's stripped below, after junk filtering, so a junk
        # sibling can't change the stripping decision either (Finding 4).
        normalized: list[tuple[zipfile.ZipInfo, str]] = []
        for info in members:
            try:
                path = normalize_path(info.filename)
            except InvalidPath as exc:
                raise InvalidArchive(exc.reason, entry=info.filename) from exc
            normalized.append((info, path))

        safe = [(info, path) for info, path in normalized if not _is_junk(path)]
        prefix = _common_prefix([path for _, path in safe])

        entries: list[ArchiveEntry] = []
        seen: dict[str, str] = {}
        total = 0
        budget = settings.latex_project_max_bytes

        for info, path in safe:
            final_path = path[len(prefix) :] if prefix else path
            if not final_path:
                continue

            key = collision_key(final_path)
            if key in seen:
                raise InvalidArchive(f"collides with {seen[key]}", entry=info.filename)
            seen[key] = final_path

            data = _read_bounded(zf, info, budget - total)
            total += len(data)
            entries.append(
                ArchiveEntry(path=final_path, data=data, is_binary=classify_binary(data))
            )

    if not entries:
        raise InvalidArchive("the archive contains no usable files")
    return entries
