"""add paper body column

Revision ID: 028bd5a7845c
Revises: c1d2e3f4a5b6
Create Date: 2026-06-28 19:38:27.496917
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '028bd5a7845c'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('conversation_message_embeddings_embedding_idx'), table_name='conversation_message_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('paper_chunk_embeddings_embedding_idx'), table_name='paper_chunk_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('papers', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'body')
    op.create_index(op.f('paper_chunk_embeddings_embedding_idx'), 'paper_chunk_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('conversation_message_embeddings_embedding_idx'), 'conversation_message_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
