"""add_project_id_to_research_runs

Revision ID: 41fef8e9ff63
Revises: 4fd85b4bd951
Create Date: 2026-06-27 14:09:13.498668
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41fef8e9ff63'
down_revision: Union[str, None] = '4fd85b4bd951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_runs', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_research_runs_project_id'), 'research_runs', ['project_id'], unique=False)
    op.create_foreign_key(None, 'research_runs', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_runs', type_='foreignkey')
    op.drop_index(op.f('ix_research_runs_project_id'), table_name='research_runs')
    op.drop_column('research_runs', 'project_id')
    # ### end Alembic commands ###
