"""add project color

Revision ID: 66b47d9d45e3
Revises: 2b3c4d5e6f7a
Create Date: 2026-08-20 20:43:07.471090
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "66b47d9d45e3"
down_revision: Union[str, None] = "2b3c4d5e6f7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("color", sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "color")
    # ### end Alembic commands ###
