"""latex document grants

Revision ID: a26d355c4d98
Revises: 18233b03153e
Create Date: 2026-08-20 23:23:05.133668
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "a26d355c4d98"
down_revision: Union[str, None] = "18233b03153e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "latex_document_members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["latex_documents.id"],
            name="fk_latex_document_members_document_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_latex_document_members_user_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "user_id"),
    )
    op.create_index(
        op.f("ix_latex_document_members_document_id"),
        "latex_document_members",
        ["document_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping this table destroys every per-document editor/viewer grant it
    # holds -- correct and unavoidable (the schema being removed IS the
    # grants), but silent otherwise: this is one-way data loss, not a
    # reversible schema change.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_latex_document_members_document_id"), table_name="latex_document_members"
    )
    op.drop_table("latex_document_members")
    # ### end Alembic commands ###
