"""add paper_files and resolved_pdf_url

Revision ID: d7fde275b721
Revises: a26d355c4d98
Create Date: 2026-08-22 01:50:15.631652
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d7fde275b721"
down_revision: Union[str, None] = "a26d355c4d98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_files",
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("blob", sa.LargeBinary(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.id"], name="fk_paper_files_paper_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("paper_id"),
    )
    op.add_column("papers", sa.Column("resolved_pdf_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "resolved_pdf_url")
    op.drop_table("paper_files")
    # ### end Alembic commands ###
